var I18N = {
  data: {
    zh: {
      lang_zh: "中文", lang_en: "EN", lang_ja: "日", lang_tw: "繁",
      nav_home: "首页", nav_articles: "文档", nav_about: "关于",
      articles_title: "快速导航", articles_category: "分类", articles_tags: "标签",
      articles_date: "发布日期", articles_back: "返回首页",
      footer_updated: "最后更新", footer_contact: "联系方式",
      stats_runbooks: "运维手册", stats_sops: "标准操作", stats_refs: "快速参考",
      hero_title: "SRE Wiki", hero_subtitle: "站可靠性工程文档中心",
      feat_runbook_title: "运维手册", feat_runbook_desc: "标准化的故障排查手册，含诊断步骤",
      feat_sop_title: "标准操作", feat_sop_desc: "标准操作流程，保证一致性和安全性",
      feat_ref_title: "快速参考", feat_ref_desc: "常用命令和配置速查表",
      article_category: "分类", article_tags: "标签", article_date: "日期",
      about_title: "关于我", about_subtitle: "了解我更多",
      about_bio: "热爱技术的 SRE 工程师，专注于保障服务稳定性。业余时间喜欢研究新技术、收集手办、刷 B 站。",
      about_motto: "只要不影响到他人，自己爱做什么都好",
      like_text: "点赞",
      db_title: "数据库故障转移手册", db_precheck: "预先检查",
      db_precheck_1: "验证应用服务器无法连接主数据库",
      db_precheck_2: "检查监控告警确认数据库健康状态",
      db_step1: "步骤 1：确认主库故障", db_step2: "步骤 2：提升从库",
      db_step3: "步骤 3：更新连接字符串", db_verify: "验证",
      db_verify_1: "从应用服务器测试连接",
      db_verify_2: "监控剩余从库的复制延迟",
      db_verify_3: "确认只读从库已指向新主库",
      sr_title: "服务重启手册", sr_when: "何时使用",
      sr_when_desc: "服务无响应、返回 5xx 错误、或请求挂起时使用此手册。",
      sr_step1: "步骤 1：检查服务状态", sr_step2: "步骤 2：检查资源使用",
      sr_step3: "步骤 3：重启服务", sr_step4: "步骤 4：验证健康状态",
      sr_step5: "步骤 5：监控 5 分钟",
      sr_step5_desc: "在 Grafana 中观察错误率和延迟。",
      sr_escalation: "升级处理",
      sr_escalation_desc: "如果重启失败或服务反复崩溃，请升级到 #sre-incidents 群组。",
      ir_title: "事件响应标准操作流程", ir_severity: "严重等级",
      ir_level: "等级", ir_response_time: "响应时间", ir_example: "示例",
      ir_p1_time: "15 分钟", ir_p1_desc: "完全宕机、数据丢失",
      ir_p2_time: "1 小时", ir_p2_desc: "部分服务中断",
      ir_p3_time: "4 小时", ir_p3_desc: "性能下降",
      ir_response_steps: "响应步骤",
      ir_step1: "1. 确认事件", ir_step1_1: "在 PagerDuty 中认领事件",
      ir_step1_2: "创建事件频道: #inc-YYYYMMDD-描述",
      ir_step2: "2. 评估", ir_step2_1: "查看监控仪表盘",
      ir_step2_2: "确定影响范围",
      ir_step2_3: "分配角色: 负责人、沟通者、技术支持",
      ir_step3: "3. 缓解", ir_step3_1: "每 15 分钟更新一次状态",
      ir_step3_2: "优先采用最快的缓解方案", ir_step3_3: "实时记录操作",
      ir_step4: "4. 解决", ir_step4_1: "确认指标恢复正常",
      ir_step4_2: "更新状态页面", ir_step4_3: "在 PagerDuty 中关闭事件",
      ir_step5: "5. 后续跟进", ir_step5_1: "48 小时内安排复盘会议",
      ir_step5_2: "在 Jira 中创建待办事项", ir_step5_3: "如有遗漏则更新运维手册",
      ir_contacts: "联系方式", ir_oncall: "值班 SRE: PagerDuty",
      ir_eng_lead: "工程负责人: @eng-lead", ir_mgt: "管理层: @mgt-oncall",
      aqr_title: "告警快速参考", aqr_p1_header: "高优先级 (P1)",
      aqr_cpu: "CPU > 90% 持续 5 分钟", aqr_mem: "内存 > 95% 持续 5 分钟",
      aqr_disk: "磁盘使用 > 90%", aqr_p2_header: "中优先级 (P2)",
      aqr_resp_time: "响应时间 > 2 秒",
      aqr_resp_time_1: "检查应用日志中的慢查询",
      aqr_resp_time_2: "检查上游服务健康状态",
      aqr_resp_time_3: "必要时扩容: kubectl scale deployment --replicas=+2",
      aqr_err_rate: "错误率 > 1%", aqr_err_rate_1: "检查最近的部署",
      aqr_err_rate_2: "必要时回滚: helm rollback <release>",
      aqr_io_wait: "磁盘 I/O 等待 > 20%", aqr_p3_header: "低优先级 (P3)",
      aqr_cert: "证书到期 < 30 天", aqr_conn_pool: "连接池使用 > 80%",
      aqr_conn_pool_desc: "检查应用连接池设置，必要时扩容数据库。",
      dd_title: "Docker 调试命令", dd_inspect: "容器检查",
      dd_inside: "进入容器内部", dd_network: "网络调试",
      dd_perf: "性能", dd_cleanup: "清理",
      kpd_title: "K8s Pod 调试手册", kpd_quick: "快速检查",
      kpd_restart: "重启问题", kpd_resource: "资源问题",
      kpd_network: "网络调试", kpd_shell: "进入 Pod Shell",
      kpd_fix: "常见修复",
      link_database_failover: "数据库故障转移",
      link_service_restart: "服务重启",
      link_incident_response: "事件响应",
      link_alert_quick_reference: "告警快速参考",
      link_docker_debug: "Docker 调试", link_k8s_pod_debug: "K8s Pod 调试",
      interest_anime: "二次元", interest_figures: "手办收藏",
      interest_sre: "SRE", interest_hacking: "黑客技术",
      qr_title: "扫码添加", qr_desc: "打开对应APP扫描二维码",
      qr_close: "关闭", qr_wechat: "微信扫码添加",
      about_page_title: "关于 - Thorvald",
      social_bilibili: "B站", social_youtube: "YouTube",
      social_email: "邮箱", social_wechat: "微信",
      social_x: "X", social_github: "GitHub"
    },
    en: {
      lang_zh: "Chinese", lang_en: "EN", lang_ja: "JP", lang_tw: "TW",
      nav_home: "Home", nav_articles: "Docs", nav_about: "About",
      articles_title: "Quick Navigation", articles_category: "Category",
      articles_tags: "Tags", articles_date: "Published", articles_back: "Back to Home",
      footer_updated: "Last updated", footer_contact: "Contact",
      stats_runbooks: "Runbooks", stats_sops: "SOPs", stats_refs: "References",
      hero_title: "SRE Wiki", hero_subtitle: "Site Reliability Engineering Documentation Center",
      feat_runbook_title: "Runbook", feat_runbook_desc: "Standardized troubleshooting manuals with diagnostic steps",
      feat_sop_title: "SOP", feat_sop_desc: "Standard operating procedures for consistency and safety",
      feat_ref_title: "Reference", feat_ref_desc: "Common commands and configuration quick reference",
      article_category: "Category", article_tags: "Tags", article_date: "Date",
      about_title: "About Me", about_subtitle: "Learn more about me",
      about_bio: "SRE engineer passionate about technology, focused on ensuring service stability. In spare time, I enjoy researching new tech, collecting figures, and browsing Bilibili.",
      about_motto: "As long as it doesn't affect others, feel free to do whatever you want",
      like_text: "Like",
      db_title: "Database Failover Runbook", db_precheck: "Pre-check",
      db_precheck_1: "Verify primary DB is unreachable from app servers",
      db_precheck_2: "Check monitoring alerts for DB health",
      db_step1: "Step 1: Identify Primary Failure", db_step2: "Step 2: Promote Replica",
      db_step3: "Step 3: Update Connection String", db_verify: "Verification",
      db_verify_1: "Test connection from app servers",
      db_verify_2: "Monitor replication lag on remaining replicas",
      db_verify_3: "Verify read replicas are pointing to new primary",
      sr_title: "Service Restart Runbook", sr_when: "When to Use",
      sr_when_desc: "Use when service is unresponsive, returning 5xx errors, or hanging requests.",
      sr_step1: "Step 1: Check Service Status", sr_step2: "Step 2: Check Resource Usage",
      sr_step3: "Step 3: Restart Service", sr_step4: "Step 4: Verify Health",
      sr_step5: "Step 5: Monitor for 5 minutes",
      sr_step5_desc: "Watch error rates and latency in Grafana.",
      sr_escalation: "Escalation",
      sr_escalation_desc: "If restart fails or service crashes repeatedly, escalate to #sre-incidents.",
      ir_title: "Incident Response SOP", ir_severity: "Severity Levels",
      ir_level: "Level", ir_response_time: "Response Time", ir_example: "Example",
      ir_p1_time: "15 min", ir_p1_desc: "Full outage, data loss",
      ir_p2_time: "1 hour", ir_p2_desc: "Partial outage",
      ir_p3_time: "4 hours", ir_p3_desc: "Degraded performance",
      ir_response_steps: "Response Steps",
      ir_step1: "1. Acknowledge", ir_step1_1: "Claim incident in PagerDuty",
      ir_step1_2: "Create incident channel: #inc-YYYYMMDD-description",
      ir_step2: "2. Assess", ir_step2_1: "Check monitoring dashboards",
      ir_step2_2: "Identify blast radius",
      ir_step2_3: "Assign roles: Lead, Comms, Tech",
      ir_step3: "3. Mitigate", ir_step3_1: "Communicate status every 15 min",
      ir_step3_2: "Apply fastest mitigation first", ir_step3_3: "Document actions in real-time",
      ir_step4: "4. Resolve", ir_step4_1: "Confirm metrics return to normal",
      ir_step4_2: "Update status page", ir_step4_3: "Close incident in PagerDuty",
      ir_step5: "5. Follow-up", ir_step5_1: "Schedule post-mortem within 48h",
      ir_step5_2: "Create action items in Jira", ir_step5_3: "Update runbooks if gaps found",
      ir_contacts: "Contacts", ir_oncall: "On-call SRE: PagerDuty",
      ir_eng_lead: "Engineering Lead: @eng-lead", ir_mgt: "Management: @mgt-oncall",
      aqr_title: "Alert Quick Reference", aqr_p1_header: "High Priority (P1)",
      aqr_cpu: "CPU > 90% for 5min", aqr_mem: "Memory > 95% for 5min",
      aqr_disk: "Disk > 90%", aqr_p2_header: "Medium Priority (P2)",
      aqr_resp_time: "Response Time > 2s",
      aqr_resp_time_1: "Check app logs for slow queries",
      aqr_resp_time_2: "Check upstream service health",
      aqr_resp_time_3: "Scale if needed: kubectl scale deployment --replicas=+2",
      aqr_err_rate: "Error Rate > 1%", aqr_err_rate_1: "Check recent deployments",
      aqr_err_rate_2: "Rollback if necessary: helm rollback <release>",
      aqr_io_wait: "Disk I/O Wait > 20%", aqr_p3_header: "Low Priority (P3)",
      aqr_cert: "Certificate Expiry < 30 days", aqr_conn_pool: "Connection Pool > 80%",
      aqr_conn_pool_desc: "Check application connection pool settings and scale database if needed.",
      dd_title: "Docker Debug Commands", dd_inspect: "Container Inspection",
      dd_inside: "Inside the Container", dd_network: "Network Debugging",
      dd_perf: "Performance", dd_cleanup: "Cleanup",
      kpd_title: "K8s Pod Debug Runbook", kpd_quick: "Quick Checks",
      kpd_restart: "Restart Issues", kpd_resource: "Resource Issues",
      kpd_network: "Network Debug", kpd_shell: "Access Pod Shell",
      kpd_fix: "Common Fixes",
      link_database_failover: "Database Failover",
      link_service_restart: "Service Restart",
      link_incident_response: "Incident Response",
      link_alert_quick_reference: "Alert Quick Reference",
      link_docker_debug: "Docker Debug", link_k8s_pod_debug: "K8s Pod Debug",
      interest_anime: "Anime", interest_figures: "Figure Collection",
      interest_sre: "SRE", interest_hacking: "Hacking",
      qr_title: "Scan to Add", qr_desc: "Open the app and scan the QR code",
      qr_close: "Close", qr_wechat: "WeChat QR Code",
      about_page_title: "About - Thorvald",
      social_bilibili: "Bilibili", social_youtube: "YouTube",
      social_email: "Email", social_wechat: "WeChat",
      social_x: "X", social_github: "GitHub"
    },
    ja: {
      lang_zh: "中国語", lang_en: "英語", lang_ja: "日本語", lang_tw: "繁体字",
      nav_home: "ホーム", nav_articles: "ドキュメント", nav_about: "概要",
      articles_title: "クイックナビゲーション", articles_category: "カテゴリー",
      articles_tags: "タグ", articles_date: "公開日", articles_back: "ホームに戻る",
      footer_updated: "最終更新", footer_contact: "連絡先",
      stats_runbooks: "ランブック", stats_sops: "標準操作", stats_refs: "リファレンス",
      hero_title: "SRE Wiki", hero_subtitle: "サイト信頼性エンジニアリングドキュメントセンター",
      feat_runbook_title: "ランブック", feat_runbook_desc: "診断手順を含む標準化されたトラブルシューティングマニュアル",
      feat_sop_title: "標準操作", feat_sop_desc: "一貫性と安全性を確保するための標準操作手順",
      feat_ref_title: "リファレンス", feat_ref_desc: "一般的なコマンドと構成のクイックリファレンス",
      article_category: "カテゴリー", article_tags: "タグ", article_date: "日付",
      about_title: "概要", about_subtitle: "もっと私について",
      about_bio: "サービス安定性の確保に注力する技術愛好家のSREエンジニア。空き時間には新技術の研究、フィギュア収集、B站閲覧を楽しんでいます。",
      about_motto: "他人影響を与えない限り、自分の好きなことをすれば良い",
      like_text: "いいね",
      db_title: "データベースフェイルオーバーランブック", db_precheck: "事前確認",
      db_precheck_1: "アプリサーバーから主DBに接続できないことを確認",
      db_precheck_2: "監視アラートでDBの状態を確認",
      db_step1: "ステップ 1：主库的故障を確認", db_step2: "ステップ 2：レプリカを昇格",
      db_step3: "ステップ 3：接続文字列を更新", db_verify: "検証",
      db_verify_1: "アプリサーバーから接続テスト",
      db_verify_2: "残りのレプリカの複製遅延を監視",
      db_verify_3: "読み取りレプリカが新しい主库を指していることを確認",
      sr_title: "サービス再起動ランブック", sr_when: "使用タイミング",
      sr_when_desc: "サービスが応答しない、5xxエラーを返す、またはリクエストがハングした場合に使用。",
      sr_step1: "ステップ 1：サービスの状態を確認", sr_step2: "ステップ 2：リソース使用量をチェック",
      sr_step3: "ステップ 3：サービスを再起動", sr_step4: "ステップ 4：健康状態を確認",
      sr_step5: "ステップ 5：5分間監視",
      sr_step5_desc: "Grafanaでエラー率と遅延を監視。",
      sr_escalation: "エスカレーション",
      sr_escalation_desc: "再起動に失敗하거나サービス反复崩壊する場合は、#sre-incidentsにエスカレーション。",
      ir_title: "インシデント対応標準操作", ir_severity: "重大度レベル",
      ir_level: "レベル", ir_response_time: "対応時間", ir_example: "例",
      ir_p1_time: "15分", ir_p1_desc: "完全ダウン、データ損失",
      ir_p2_time: "1時間", ir_p2_desc: "部分的なサービス中断",
      ir_p3_time: "4時間", ir_p3_desc: "パフォーマンス低下",
      ir_response_steps: "対応ステップ",
      ir_step1: "1. 確認", ir_step1_1: "PagerDutyでインシデントをクレーム",
      ir_step1_2: "インシデントチャンネルを作成: #inc-YYYYMMDD-説明",
      ir_step2: "2. 評価", ir_step2_1: "監視ダッシュボードを確認",
      ir_step2_2: "影響範囲を特定",
      ir_step2_3: "役割を割り当て: リード、コミunications、テクノロジー",
      ir_step3: "3. 緩和", ir_step3_1: "15分ごとに状況を通信",
      ir_step3_2: "最も早い緩和手段を優先して適用", ir_step3_3: "リアルタイムでアクションを記録",
      ir_step4: "4. 解決", ir_step4_1: "指標が正常に戻ったことを確認",
      ir_step4_2: "ステータスを更新", ir_step4_3: "PagerDutyでインシデントをクローズ",
      ir_step5: "5. フォローアップ", ir_step5_1: "48時間以内にポストモーテムをスケジュール",
      ir_step5_2: "Jiraでアクションアイテムを作成", ir_step5_3: "ギャップが見つかった場合はランブックを更新",
      ir_contacts: "連絡先", ir_oncall: "オンコール SRE: PagerDuty",
      ir_eng_lead: "エンジニアリングリード: @eng-lead", ir_mgt: "マネジメント: @mgt-oncall",
      aqr_title: "アラートクイックリファレンス", aqr_p1_header: "高優先度 (P1)",
      aqr_cpu: "CPU > 90% 5分間", aqr_mem: "メモリ > 95% 5分間",
      aqr_disk: "ディスク > 90%", aqr_p2_header: "中優先度 (P2)",
      aqr_resp_time: "応答時間 > 2秒",
      aqr_resp_time_1: "アプリログで遅いクエリを確認",
      aqr_resp_time_2: "上游サービスの健康状態を確認",
      aqr_resp_time_3: "必要に応じてスケール: kubectl scale deployment --replicas=+2",
      aqr_err_rate: "エラー率 > 1%", aqr_err_rate_1: "最近のデプロイを確認",
      aqr_err_rate_2: "必要に応じてロールバック: helm rollback <release>",
      aqr_io_wait: "ディスクI/O待機 > 20%", aqr_p3_header: "低優先度 (P3)",
      aqr_cert: "証明書失効 < 30日", aqr_conn_pool: "接続プール > 80%",
      aqr_conn_pool_desc: "アプリケーション接続プール設定を確認し、必要に応じてデータベースをスケール。",
      dd_title: "Dockerデバッグコマンド", dd_inspect: "コンテナ検査",
      dd_inside: "コンテナ内に入る", dd_network: "ネットワークデバッグ",
      dd_perf: "パフォーマンス", dd_cleanup: "クリーンアップ",
      kpd_title: "K8s Podデバッグランブック", kpd_quick: "クイックチェック",
      kpd_restart: "再起動の問題", kpd_resource: "リソースの問題",
      kpd_network: "ネットワークデバッグ", kpd_shell: "Podシェルにアクセス",
      kpd_fix: "一般的な修正",
      link_database_failover: "データベースフェイルオーバー",
      link_service_restart: "サービス再起動",
      link_incident_response: "インシデント対応",
      link_alert_quick_reference: "アラートクイックリファレンス",
      link_docker_debug: "Dockerデバッグ", link_k8s_pod_debug: "K8s Podデバッグ",
      interest_anime: "アニメ", interest_figures: "フィギュア收藏",
      interest_sre: "SRE", interest_hacking: "ハッキング",
      qr_title: "スキャンして追加", qr_desc: "対応APPを開いてQRコードをスキャン",
      qr_close: "閉じる", qr_wechat: "WeChat QRコード",
      about_page_title: "概要 - Thorvald",
      social_bilibili: "B站", social_youtube: "YouTube",
      social_email: "メール", social_wechat: "WeChat",
      social_x: "X", social_github: "GitHub"
    },
    "zh-TW": {
      lang_zh: "簡體中文", lang_en: "English", lang_ja: "日本語", lang_tw: "繁體中文",
      nav_home: "首頁", nav_articles: "文檔", nav_about: "關於",
      articles_title: "快速導航", articles_category: "分類",
      articles_tags: "標籤", articles_date: "發布日期", articles_back: "返回首頁",
      footer_updated: "最後更新", footer_contact: "聯絡方式",
      stats_runbooks: "運維手冊", stats_sops: "標準操作", stats_refs: "快速參考",
      hero_title: "SRE Wiki", hero_subtitle: "站可靠性工程文檔中心",
      feat_runbook_title: "運維手冊", feat_runbook_desc: "標準化的故障排查手冊，含診斷步驟",
      feat_sop_title: "標準操作", feat_sop_desc: "標準操作流程，保證一致性和安全性",
      feat_ref_title: "快速參考", feat_ref_desc: "常用命令和配置速查表",
      article_category: "分類", article_tags: "標籤", article_date: "日期",
      about_title: "關於我", about_subtitle: "了解更多",
      about_bio: "熱愛技術的 SRE 工程師，專注於保障服務穩定性。業餘時間喜歡研究新技術、收集手辦、刷 B 站。",
      about_motto: "只要不影響到他人，自己愛做什麼都好",
      like_text: "讚",
      db_title: "資料庫故障轉移手冊", db_precheck: "預先檢查",
      db_precheck_1: "驗證應用服務器無法連接主資料庫",
      db_precheck_2: "檢查監控告警確認資料庫健康狀態",
      db_step1: "步驟 1：確認主庫故障", db_step2: "步驟 2：提升從庫",
      db_step3: "步驟 3：更新連接字串", db_verify: "驗證",
      db_verify_1: "從應用服務器測試連接",
      db_verify_2: "監控剩餘從庫的複製延遲",
      db_verify_3: "確認唯讀從庫已指向新主庫",
      sr_title: "服務重啟手冊", sr_when: "何時使用",
      sr_when_desc: "服務無響應、返回 5xx 錯誤、或請求掛起時使用此手冊。",
      sr_step1: "步驟 1：檢查服務狀態", sr_step2: "步驟 2：檢查資源使用",
      sr_step3: "步驟 3：重啟服務", sr_step4: "步驟 4：驗證健康狀態",
      sr_step5: "步驟 5：監控 5 分鐘",
      sr_step5_desc: "在 Grafana 中觀察錯誤率和延遲。",
      sr_escalation: "升級處理",
      sr_escalation_desc: "如果重啟失敗或服務反覆崩潰，請升級到 #sre-incidents 群組。",
      ir_title: "事件響應標準操作流程", ir_severity: "嚴重等級",
      ir_level: "等級", ir_response_time: "響應時間", ir_example: "範例",
      ir_p1_time: "15 分鐘", ir_p1_desc: "完全停機、資料遺失",
      ir_p2_time: "1 小時", ir_p2_desc: "部分服務中斷",
      ir_p3_time: "4 小時", ir_p3_desc: "效能下降",
      ir_response_steps: "響應步驟",
      ir_step1: "1. 確認事件", ir_step1_1: "在 PagerDuty 中認領事件",
      ir_step1_2: "建立事件頻道: #inc-YYYYMMDD-描述",
      ir_step2: "2. 評估", ir_step2_1: "查看監控儀表板",
      ir_step2_2: "確定影響範圍",
      ir_step2_3: "分配角色: 負責人、溝通者、技術支援",
      ir_step3: "3. 緩解", ir_step3_1: "每 15 分鐘更新一次狀態",
      ir_step3_2: "優先採用最快的緩解方案", ir_step3_3: "即時記錄操作",
      ir_step4: "4. 解決", ir_step4_1: "確認指標恢復正常",
      ir_step4_2: "更新狀態頁面", ir_step4_3: "在 PagerDuty 中關閉事件",
      ir_step5: "5. 後續跟進", ir_step5_1: "48 小時內安排复盘會議",
      ir_step5_2: "在 Jira 中建立待辦事項", ir_step5_3: "如有遺漏則更新運維手冊",
      ir_contacts: "聯絡方式", ir_oncall: "值班 SRE: PagerDuty",
      ir_eng_lead: "工程負責人: @eng-lead", ir_mgt: "管理層: @mgt-oncall",
      aqr_title: "告警快速參考", aqr_p1_header: "高優先級 (P1)",
      aqr_cpu: "CPU > 90% 持續 5 分鐘", aqr_mem: "記憶體 > 95% 持續 5 分鐘",
      aqr_disk: "磁碟使用 > 90%", aqr_p2_header: "中優先級 (P2)",
      aqr_resp_time: "響應時間 > 2 秒",
      aqr_resp_time_1: "檢查應用日誌中的慢查詢",
      aqr_resp_time_2: "檢查上游服務健康狀態",
      aqr_resp_time_3: "必要時擴容: kubectl scale deployment --replicas=+2",
      aqr_err_rate: "錯誤率 > 1%", aqr_err_rate_1: "檢查最近的部署",
      aqr_err_rate_2: "必要時回滾: helm rollback <release>",
      aqr_io_wait: "磁碟 I/O 等待 > 20%", aqr_p3_header: "低優先級 (P3)",
      aqr_cert: "憑證到期 < 30 天", aqr_conn_pool: "連接池使用 > 80%",
      aqr_conn_pool_desc: "檢查應用連接池設定，必要時擴容資料庫。",
      dd_title: "Docker 調試命令", dd_inspect: "容器檢查",
      dd_inside: "進入容器內部", dd_network: "網路調試",
      dd_perf: "效能", dd_cleanup: "清理",
      kpd_title: "K8s Pod 調試手冊", kpd_quick: "快速檢查",
      kpd_restart: "重啟問題", kpd_resource: "資源問題",
      kpd_network: "網路調試", kpd_shell: "進入 Pod Shell",
      kpd_fix: "常見修復",
      link_database_failover: "資料庫故障轉移",
      link_service_restart: "服務重啟",
      link_incident_response: "事件響應",
      link_alert_quick_reference: "告警快速參考",
      link_docker_debug: "Docker 調試", link_k8s_pod_debug: "K8s Pod 調試",
      interest_anime: "二次元", interest_figures: "手辦收藏",
      interest_sre: "SRE", interest_hacking: "黑客技術",
      qr_title: "掃碼添加", qr_desc: "打開對應APP掃描二維碼",
      qr_close: "關閉", qr_wechat: "微信掃碼添加",
      about_page_title: "關於 - Thorvald",
      social_bilibili: "B站", social_youtube: "YouTube",
      social_email: "郵箱", social_wechat: "微信",
      social_x: "X", social_github: "GitHub"
    }
  },
  current: "zh",
  init: function() {
    var saved = localStorage.getItem("sre-wiki-lang");
    if (saved && this.data[saved]) this.current = saved;
    this.apply();
  },
  switchTo: function(lang) {
    if (this.data[lang]) {
      this.current = lang;
      localStorage.setItem("sre-wiki-lang", lang);
      this.apply();
      document.querySelectorAll('.lang-btn').forEach(function(btn) {
        btn.classList.remove('active');
      });
      var btn = document.querySelector('.lang-btn[onclick*="switchTo(\'' + lang + '\')"]');
      if (btn) btn.classList.add('active');
    }
  },
  t: function(key) {
    return (this.data[this.current] && this.data[this.current][key]) ? this.data[this.current][key] : (this.data.zh[key] || key);
  },
  apply: function() {
    var self = this;
    document.querySelectorAll("[data-i18n]").forEach(function(el) {
      var key = el.getAttribute("data-i18n");
      el.textContent = self.t(key);
    });
    document.querySelectorAll('.lang-btn[data-i18n]').forEach(function(btn) {
      var key = btn.getAttribute("data-i18n");
      btn.textContent = self.t(key);
    });
    document.documentElement.lang = this.current;
  }
};
document.addEventListener("DOMContentLoaded", function() { I18N.init(); });